--- 
repositories:
  clone_path: '~/repos'
  repos:
  - xlsx-compare: https://github.com/kurekszymon/xlsx-compare
  - roomeo: https://github.com/kurekszymon/roomeo
  - yaml-cpp: https://github.com/jbeder/yaml-cpp
  - fargo-bitbucket: https://bitbucket.org/fargo3d/public.git
custom_scripts:
  - echo: echo "hello world"
  - ls: ls
  - mkdir: mkdir ~/hello_crpp
languages: 
  - cpp: 
    - emscripten: https://github.com/emscripten-core/emsdk.git
    - cmake: 'cmake-123'
    - ninja: 'ninja-123'
  - python: 
    - pyenv: '3'
  - js:
    - nvm: v0.40.1
    - node: 'v8-123'
